# Generated by Django 6.0.7 on 2026-07-09 23:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("estudos", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="avaliacao",
            name="materia",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="avaliacoes",
                to="estudos.materia",
            ),
        ),
        migrations.AlterField(
            model_name="curso",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cursos",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="falta",
            name="materia",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="faltas",
                to="estudos.materia",
            ),
        ),
        migrations.AlterField(
            model_name="lembrete",
            name="avaliacao",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lembretes",
                to="estudos.avaliacao",
            ),
        ),
        migrations.AlterField(
            model_name="materia",
            name="curso",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="materias",
                to="estudos.curso",
            ),
        ),
        migrations.AlterField(
            model_name="materia",
            name="docente",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="materias",
                to="estudos.docente",
            ),
        ),
        migrations.AlterField(
            model_name="topico",
            name="materia",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="topicos",
                to="estudos.materia",
            ),
        ),
        migrations.AlterField(
            model_name="topico",
            name="tecnica_estudo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="topicos",
                to="estudos.tecnicaestudo",
            ),
        ),
        migrations.CreateModel(
            name="SessaoEstudo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("duracao_minutos", models.IntegerField()),
                ("data", models.DateTimeField(auto_now_add=True)),
                (
                    "topico",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessoes_estudo",
                        to="estudos.topico",
                    ),
                ),
            ],
        ),
    ]
